FROM python:3.9.6-alpine
RUN bash
WORKDIR /path/to/workdir
RUN python -m venv .
RUN source venv/bin/activate
COPY pip_requirement.install ./
RUN echo 'Copy the pip requirement to the workdir.'
RUN pip3 install -r pip_requirement.install
RUN echo 'Build python env success.'
RUN mkdir workspace
COPY ./workspace/* ./workspace/*
RUN echo 'Move the source files to the workdir.'
ENV GECHODRIVER_HOME=/Users/pocky/Program/bin/geckodrivers
# CMD ['python', 'workspace/trick_slideshow.py']
RUN echo 'Run trick script success.'
